<?php

namespace DoctrineProxies\__CG__\App\Domain\Model\Employee;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Employee extends \App\Domain\Model\Employee\Employee implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Domain\\Model\\Employee\\Employee' . "\0" . 'id', '' . "\0" . 'App\\Domain\\Model\\Employee\\Employee' . "\0" . 'name', '' . "\0" . 'App\\Domain\\Model\\Employee\\Employee' . "\0" . 'pharmacy', '' . "\0" . 'App\\Domain\\Model\\Employee\\Employee' . "\0" . 'birthdate', '' . "\0" . 'App\\Domain\\Model\\Employee\\Employee' . "\0" . 'gender'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Domain\\Model\\Employee\\Employee' . "\0" . 'id', '' . "\0" . 'App\\Domain\\Model\\Employee\\Employee' . "\0" . 'name', '' . "\0" . 'App\\Domain\\Model\\Employee\\Employee' . "\0" . 'pharmacy', '' . "\0" . 'App\\Domain\\Model\\Employee\\Employee' . "\0" . 'birthdate', '' . "\0" . 'App\\Domain\\Model\\Employee\\Employee' . "\0" . 'gender'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Employee $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): \App\Domain\Model\Employee\EmployeeId
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): \App\Domain\Model\Employee\Name
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function changeName(\App\Domain\Model\Employee\Name $name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'changeName', [$name]);

        return parent::changeName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthdate(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthdate', []);

        return parent::getBirthdate();
    }

    /**
     * {@inheritDoc}
     */
    public function changeBirthDate(\DateTime $birthDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'changeBirthDate', [$birthDate]);

        return parent::changeBirthDate($birthDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getGender(): \App\Domain\Model\Employee\Gender
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', []);

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function changeGender(\App\Domain\Model\Employee\Gender $gender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'changeGender', [$gender]);

        return parent::changeGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function getPharmacy(): \App\Domain\Model\Pharmacy\Pharmacy
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPharmacy', []);

        return parent::getPharmacy();
    }

}
